#!/usr/bin/env sh

# focus window
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east 

# swap windows
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east

# move windows
shift + cmd - h : yabai -m window --warp west
shift + cmd - j : yabai -m window --warp south
shift + cmd - k : yabai -m window --warp north
shift + cmd - l : yabai -m window --warp east

# move floating window
shift + ctrl - a : yabai -m window --move rel:-25:0
shift + ctrl - s : yabai -m window --move rel:0:25
shift + ctrl - d : yabai -m window --move rel:25:0
shift + ctrl - w : yabai -m window --move rel:0:-25

# increase window size
shift + cmd - a : yabai -m window --resize left:-50:0
shift + cmd - w : yabai -m window --resize top:0:-25
shift + cmd - d : yabai -m window --resize right:50:0
shift + cmd - s : yabai -m window --resize bottom:0:25

# decrease window size
shift + alt - s : yabai -m window --resize bottom:0:-25
shift + alt - w : yabai -m window --resize top:0:25
shift + alt - a : yabai -m window --resize left:50:0
shift + alt - d : yabai -m window --resize right:-50:0

# toggle window zoom
alt - d : yabai -m window --toggle zoom-parent
alt - f : yabai -m window --toggle zoom-fullscreen

# toggle window split type
alt - e : yabai -m window --toggle split

# focus monitor
ctrl + alt - 1  : yabai -m display --focus 1
ctrl + alt - 2  : yabai -m display --focus 2
ctrl + alt - 3  : yabai -m display --focus 3

# float windows set
ctrl + alt - 0 : yabai -m space --balance   # balance the size of windows
alt - r : yabai -m space --rotate 90        # rotate


# resize windows
ctrl + alt + cmd - left : yabai -m window --resize left:-50:0; yabai -m window --resize right:-50:0
ctrl + alt + cmd - down : yabai -m window --resize bottom:0:50; yabai -m window --resize top:0:50
ctrl + alt + cmd - up : yabai -m window --resize top:0:-50; yabai -m window --resize bottom:0:-50
ctrl + alt + cmd - right : yabai -m window --resize right:50:0; yabai -m window --resize left:50:0

# # create space
# alt - c : ~/.config/yabai/config/create_new_space.sh 1
# # destroy sapce
# # force refresh space bar
# alt - w : ~/.config/yabai/config/destroy_space.sh

shift + cmd - n : yabai -m space --create && \
                  index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
                  yabai -m window --space "${index}" && \
                  yabai -m space --focus "${index}"

cmd + alt - n : yabai -m space --create && \
                index="$(yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index')" && \
                yabai -m space --focus "${index}"

cmd + alt - w : yabai -m space --destroy

# fast focus desktop(切换空间焦点)
# 0x32 equals to `
alt - 0x32 : ~/.config/yabai/send_to_next_display.sh
alt - tab : yabai -m space --focus recent
alt - n : yabai -m space --focus prev || yabai -m space --focus last
alt - m : yabai -m space --focus next || yabai -m space --focus first
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9
alt - 0 : yabai -m space --focus 10



# reboot Yabai
cmd + alt - r : /usr/bin/env osascript <<< "display notification \"reboot Yabai\" with title \"Yabai\""; launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"


# send window to monitor and follow focus
ctrl + cmd - c  : yabai -m window --display next; yabai -m display --focus next
ctrl + cmd - 1  : yabai -m window --display 1; yabai -m display --focus 1
ctrl + cmd - 2  : yabai -m window --display 2; yabai -m display --focus 2
ctrl + cmd - 3  : yabai -m window --display 3; yabai -m display --focus 3


# set insertion point in focused container
ctrl + alt - h : yabai -m window --insert west
ctrl + alt - l : yabai -m window --insert east
ctrl + alt - j : yabai -m window --insert south
ctrl + alt - k : yabai -m window --insert north


#float / unfloat window and center on screen
alt - t : yabai -m window --toggle float;yabai -m window --grid 4:4:1:1:2:2

