#!/usr/bin/env sh

# focus window
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east 

# swap windows
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east

# move windows
shift + cmd - h : yabai -m window --warp west
shift + cmd - j : yabai -m window --warp south
shift + cmd - k : yabai -m window --warp north
shift + cmd - l : yabai -m window --warp east

# move floating window
shift + ctrl - a : yabai -m window --move rel:-25:0
shift + ctrl - s : yabai -m window --move rel:0:25
shift + ctrl - d : yabai -m window --move rel:25:0
shift + ctrl - w : yabai -m window --move rel:0:-25

# increase window size
shift + cmd - a : yabai -m window --resize left:-50:0
shift + cmd - w : yabai -m window --resize top:0:-25
shift + cmd - d : yabai -m window --resize right:50:0
shift + cmd - s : yabai -m window --resize bottom:0:25

# decrease window size
shift + alt - s : yabai -m window --resize bottom:0:-25
shift + alt - w : yabai -m window --resize top:0:25
shift + alt - a : yabai -m window --resize left:50:0
shift + alt - d : yabai -m window --resize right:-50:0

# toggle window zoom
alt - d : yabai -m window --toggle zoom-parent
alt - f : yabai -m window --toggle zoom-fullscreen

# toggle window split type
alt - e : yabai -m window --toggle split

# focus monitor
ctrl + alt - 1  : yabai -m display --focus 1
ctrl + alt - 2  : yabai -m display --focus 2
ctrl + alt - 3  : yabai -m display --focus 3

# float windows set
ctrl + alt - 0 : yabai -m space --balance   # balance the size of windows
alt - r : yabai -m space --rotate 90        # rotate


# resize windows
ctrl + alt + cmd - left : yabai -m window --resize left:-50:0; yabai -m window --resize right:-50:0
ctrl + alt + cmd - down : yabai -m window --resize bottom:0:50; yabai -m window --resize top:0:50
ctrl + alt + cmd - up : yabai -m window --resize top:0:-50; yabai -m window --resize bottom:0:-50
ctrl + alt + cmd - right : yabai -m window --resize right:50:0; yabai -m window --resize left:50:0

# create space
alt - c : ~/.config/yabai/create_new_space.sh 1
# destroy space
# force refresh space bar
alt - w : ~/.config/yabai/destroy_space.sh

# fast focus desktop
# 0x32 equals to `
alt - 0x32 : ~/.config/yabai/send_to_next_display.sh
alt - tab : yabai -m space --focus recent
alt - p : yabai -m space --focus prev || yabai -m space --focus last
alt - n : yabai -m space --focus next || yabai -m space --focus first
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7 
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9
alt - 0 : yabai -m space --focus 10

# send current window to another space then focus
alt + cmd - tab : yabai -m window --space recent; yabai -m space --focus recent
alt + cmd - p : (yabai -m window --space prev && yabai -m space --focus prev) \
	|| (yabai -m window --space last && yabai -m space --focus last)
alt + cmd - n : (yabai -m window --space next && yabai -m space --focus next) \
	|| (yabai -m window --space first && yabai -m space --focus first)

# 0x32 equals to `
cmd + alt - 0x32 : ~/.config/yabai/send_to_next_display.sh move_window
cmd + alt - 1 : yabai -m window --space  1; yabai -m space --focus 1
cmd + alt - 2 : yabai -m window --space  2; yabai -m space --focus 2
cmd + alt - 3 : yabai -m window --space  3; yabai -m space --focus 3
cmd + alt - 4 : yabai -m window --space  4; yabai -m space --focus 4
cmd + alt - 5 : yabai -m window --space  5; yabai -m space --focus 5
cmd + alt - 6 : yabai -m window --space  6; yabai -m space --focus 6
cmd + alt - 7 : yabai -m window --space  7; yabai -m space --focus 7
cmd + alt - 8 : yabai -m window --space  8; yabai -m space --focus 8
cmd + alt - 9 : yabai -m window --space  9; yabai -m space --focus 9
cmd + alt - 0 : yabai -m window --space 10; yabai -m space --focus 10


# reboot Yabai
cmd + alt - r : /usr/bin/env osascript <<< "display notification \"reboot Yabai\" with title \"Yabai\""; launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"


# send window to monitor and follow focus
ctrl + cmd - c  : yabai -m window --display next; yabai -m display --focus next
ctrl + cmd - 1  : yabai -m window --display 1; yabai -m display --focus 1
ctrl + cmd - 2  : yabai -m window --display 2; yabai -m display --focus 2
ctrl + cmd - 3  : yabai -m window --display 3; yabai -m display --focus 3


# set insertion point in focused container
ctrl + alt - h : yabai -m window --insert west
ctrl + alt - l : yabai -m window --insert east
ctrl + alt - j : yabai -m window --insert south
ctrl + alt - k : yabai -m window --insert north

# x-axis mirror
alt - x : yabai -m space --mirror x-axis
# y-axis mirror
alt - y : yabai -m space --mirror y-axis

#float / unfloat window and center on screen
alt - t : ~/.config/yabai/toggle-window-floating-tiling.sh \
          && ~/.config/yabai/change-window-border-color-when-window-focused.sh

ctrl + alt - c : ~/.config/yabai/toggle-window-floating-tiling.sh forceCenter \
          && ~/.config/yabai/change-window-border-color-when-window-focused.sh
