#!/usr/bin/env sh

set -x

# initialization
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

source ~/.config/yabai/initialization.sh

# Signals
# Initialize the temp folder when adding or removing displays
yabai -m signal --add event=display_added action="~/.config/yabai/initialization.sh"
yabai -m signal --add event=display_removed action="~/.config/yabai/initialization.sh"
yabai -m signal --add event=window_focused action="~/.config/yabai/change-window-border-color-when-window-focused.sh"
yabai -m signal --add event=window_destroyed action="~/.config/yabai/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"
yabai -m signal --add event=application_hidden action="~/.config/yabai/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"
yabai -m signal --add event=window_minimized action="~/.config/yabai/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"

yabai -m config layout bsp
# yabai -m config --space 2 layout float

yabai -m config window_placement second_child

# Set all padding and gaps to 8pt
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_pading 8
yabai -m config right_padding 8
yabai -m config window_gap 8

yabai -m config --space 2 window_gap 2

# split ratios
yabai -m config auto_balance off
yabai -m config split_ratio 0.5

# mouse support
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus on

yabai -m config window_border on
yabai -m config window_border_placement inset
yabai -m config window_border_blur off
yabai -m config window_border_hidpi off
yabai -m config window_border_width 2
yabai -m config window_border_radius 8

yabai -m config active_window_border_color 0x817aa2f7
yabai -m config normal_window_border_color 0x72565f89


# window modifications
## window shadow
yabai -m config window_shadow float

## opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8
yabai -m config window_opacity_duration 96

# external bar
yabai -m config external_bar all:0:20

# rule

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^About This Mac$" manage=off
yabai -m rule --add app="^WeChat$" manage=off
yabai -m rule --add app="^iTerm$" manage=off
yabai -m rule --add app="^ChatGPT$" manage=off
yabai -m rule --add app="^QQ$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off

echo "yabai configuration loaded.."
